# Stage 1: Build the frontend
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json 

COPY package.json .

# Install all dependencies
RUN yarn install

# Copy the rest of the application files
COPY . .

# Expose the port for the application
EXPOSE 3000

# Start Nginx
CMD ["yarn","dev", "--port", "3000","--host"]
